-
  name: check if user "{{ user }}" exists
  command: getent passwd {{ user }}
  failed_when: user_stat.rc not in [0, 2]
  changed_when: False
  register: user_stat
-
  name: check if rustup is installed
  stat: path=~{{ user }}/.cargo/bin/rustup
  register: rustup
  when: user_stat.rc == 0
-
  name: update rustup
  command:      ~/.cargo/bin/rustup self update
  register:     result
  when:         user_stat.rc == 0 and rustup.stat.exists == True
  changed_when: result.stdout_lines | length
  become: yes
-
  name: update rustup result
  debug: msg={{ result }} verbosity=2
-
  name: update Rust
  command:      ~/.cargo/bin/rustup update
  register:     result
  when:         user_stat.rc == 0 and rustup.stat.exists == True
  changed_when: "' updated - rustc ' in result.stdout"
  failed_when: result.rc != 0 or 'update failed' in result.stdout
  become: yes
-
  name: update rust result
  debug: msg={{ result }} verbosity=2
