#!/usr/bin/python3
import os
import re
import py_compile

SHEBANG = re.compile(b'^#!/usr/bin/(python3|env python3)(\s|$)')

err = False
for dirpath, dirnames, filenames in os.walk('.'):
    if dirpath.startswith('./.git/'):
        continue
    for filename in filenames:
        path = os.path.join(dirpath, filename)
        with open(path, 'rb') as f:
            line = f.readline()
        if SHEBANG.match(line):
            bytecode_path = py_compile.compile(path)
            if bytecode_path is None:
                print()
                err = True

if err:
    exit(1)
