#!/usr/bin/python3
import glob
import pathlib
import textwrap
import yaml

yaml_files = [i.as_posix() for i in pathlib.Path().rglob('*.yml')]

err = False
for file in yaml_files:
    with open(file) as f:
        try:
            yaml.safe_load(f)
        except yaml.error.YAMLError as e:
            print('ERROR:')
            print('  file: {!r}'.format(file))
            print('  error:')
            print(textwrap.indent(str(e), '     | '))
            print()
            err = True

if err:
    exit(1)
