-
  name: install Tor
  hosts: '*'
  become: yes
  vars:
    alpha_version: 0.3.2
  vars_prompt:
    - name: version
      prompt: Tor version, Debian only ([s]table/[a]lpha/[n]ightly)
      default: stable
      private: no
  tasks:
    - fail: msg="Invalid Tor version entered '{{ version }}'"
      when: version not in ['s', 'stable', 'a', 'alpha', 'n', 'nightly']
    - name: install lsb-release
      when: ansible_distribution == 'Debian'
      apt: name=lsb-release update_cache=yes cache_valid_time=3600
    - include: install_debian.yml
      when: ansible_pkg_mgr == 'apt' and ansible_distribution == 'Debian'
              and ansible_distribution_release != 'wheezy'
              and not (ansible_lsb.id == 'Raspbian' and ansible_architecture == 'armv6l')
    - include: install_arch.yml
      when: ansible_pkg_mgr == 'pacman'
    - include: install_openbsd.yml
      when: ansible_pkg_mgr == 'openbsd_pkg'
