-
  name: install Tor
  hosts: '*'
  become: yes
  tasks:
    - include: install_debian.yml
      when: ansible_pkg_mgr == 'apt' and ansible_distribution == 'Debian' and ansible_distribution_release != 'wheezy'
    - include: install_arch.yml
      when: ansible_pkg_mgr == 'pacman'
    - include: install_openbsd.yml
      when: ansible_pkg_mgr == 'openbsd_pkg'
